config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root "home#index"
  root "home#index"
  root "forum_threads#index"

  resources :forum_threads, only: [:show, :new, :create, :edit, :update] do 
  	resources :forum_posts, only: [:create]
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
	belongs_to :user
	belongs_to :forum_thread, counter_cache: true

	validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
	belongs_to :user
	has_many :forum_posts

	validates :title, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	# create
	def create
		@thread = ForumThread.find(params[:forum_thread_id])
		@post = ForumPost.new(resource_params)

		@post.forum_thread = @thread
		@post.user = current_user

		if @post.save
			redirect_to forum_thread_path(@thread)
		else
			render 'forum_threads/show'
		end
	end

	private

	def resource_params
		params.require(:forum_post).permit(:content)
	end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :create]
	# index
	def index
		@threads = ForumThread.order(id: :desc)
	end
	# show
	def show
		@thread = ForumThread.find(params[:id])
		@post = ForumPost.new
	end

	def new
		@thread = ForumThread.new
	end

	def create
		@thread = ForumThread.new(resource_params)
		@thread.user = current_user
		if @thread.save
			redirect_to root_path
		else
			render 'new'
		end
	end


	def edit
		@thread = ForumThread.find(params[:id])
	end

	def update
		@thread = ForumThread.find(params[:id])
		@thread.user = current_user

		if @thread.update(resource_params)
			redirect_to root_path
		else
	end
end
	
	private

	def resource_params
		params.require(:forum_thread).permit(:title, :content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_threads/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<% if @thread.errors.any? %>
		<div class="alert alert-danger alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<% @thread.errors.full_messages.each do |error| %>
				<span><%= error %></span><br/>
			<%end%>
		</div>
	<%end%>

	<%= form_for @thread do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, rows: 5, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit "Edit", class: 'btn btn-primary form-control' %>
	</div>
<%end%>
</div>

app/views/forum_threads/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<% if user_signed_in? %>
		<%= link_to "Buat Diskusi", new_forum_thread_path, class: 'btn btn-primary' %>
		<%end%>
		<% @threads.each do |t| %>

			<div class="thread">
			<h4><%= link_to t.title.titleize, forum_thread_path(t) %></h4>

			<div class="meta">
				<%= I18n.l(t.created_at.to_date) %> oleh <%= t.user.name %>
			</div>

			<div class="content">
				<%= t.content %>
			</div>

			<div class="count">
				<%= t.forum_posts_count %> Obrolan
				<%= link_to "Edit", edit_forum_thread_path(t), class: 'btn btn-primary' %>
			</div>
			<div style="clear: both"></div>
		</div>

		<%end%>
	</div>
</div>

app/views/forum_threads/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<% if @thread.errors.any? %>
		<div class="alert alert-danger alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<% @thread.errors.full_messages.each do |error| %>
				<span><%= error %></span><br/>
			<%end%>
		</div>
	<%end%>

	<%= form_for @thread do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, rows: 5, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit "Create", class: 'btn btn-primary form-control' %>
	</div>
<%end%>
</div>

app/views/forum_threads/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

			<div class="thread">
			<h4><%= @thread.title.titleize %></h4>

			<div class="meta">
				<%= I18n.l(@thread.created_at.to_date) %> oleh <%= @thread.user.name %>
			</div>

			<div class="content">
				<%= @thread.content %>
			</div>
		</div>

		<% if @thread.forum_posts.any? %>
			<% @thread.forum_posts.each do |p| %>
			<div class="thread">
			<div class="meta">
				<%= I18n.l(p.created_at.to_date) %> oleh <%= p.user.name %>
			</div>

			<div class="content">
				<%= p.content %>
			</div>
		</div>
		<%end%>
		<% else %>
			<div>
				Jadilah yang pertama melakukan tanggapan.
			</div>
		<%end%>

		<% if @post.errors.any? %>
		<div class="alert alert-danger alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<% @post.errors.full_messages.each do |error| %>
				<span><%= error %></span><br/>
			<%end%>
		</div>
		<%end%>

		<% if user_signed_in? %>
		<%= form_for [@thread, @post] do |f| %>
			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, rows: 5, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.submit "Send", class: 'btn btn-primary form-control' %>
			</div>
		<%end%>
		<%end%>

	</div>
</div>

app/views/home/index.html.erb
<div>
	<h1>Halooo</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_signed_in? ? current_user.name : 'Welcome' %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Register', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
      <%end%>
    <%= yield %>
    </div>
  </body>
</html>